################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 3.0
##  \   \         Application : XAPP589, All digital VCXO.
##  /   /         Filename : AC701_picxo_example.xdc
## /___/   /\     Target board : AC701
## \   \  /  \    Timestamp : v25_0 @ Fri Apr  8 11:26:58 +0100 2016 Rev: 815:817
##  \___\/\___\
##
##
## USER CONSTRAINTS FILE FOR MGT WRAPPER EXAMPLE DESIGN
## Generated by Xilinx 7 Series FPGAs Transceivers Wizard
##
## Device:  xc7a200tfbg676-2
##
## (c) Copyright 2010-2011 Xilinx, Inc. All rights reserved.
##
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
##
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
## 
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES. 
################################################################################################################

## SFP 
set_property LOC GTPE2_CHANNEL_X0Y0 [get_cells gtwizard_0_init_i/gtwizard_0_i/U0/gt0_gtwizard_0_i/gtpe2_i]

##SMA
#set_property LOC GTPE2_CHANNEL_X0Y3 [get_cells gtwizard_0_init_i/gtwizard_0_i/U0/gt0_gtwizard_0_i/gtpe2_i]

##SMA clock
set_property LOC AB11 [get_ports  Q0_CLK1_GTREFCLK_PAD_N_IN ] 
set_property LOC AA11 [get_ports  Q0_CLK1_GTREFCLK_PAD_P_IN ]

#IOSTANDARDS
set_property IOSTANDARD LVCMOS15 [get_ports {PLL0_RESET_IN}]; 
set_property IOSTANDARD LVCMOS33 [get_ports {SFP_TX_DISABLE_OUT[0] SFP_LOS_IN[0]}]; 
set_property IOSTANDARD LVDS_25  [get_ports {SYS_CLK_P_IN SYS_CLK_N_IN}];

#SYS_CLK at 200MHz
set_property LOC P3 [get_ports  SYS_CLK_N_IN ] 
set_property LOC R3 [get_ports  SYS_CLK_P_IN ]

#Resets Push button North
set_property LOC P6 [get_ports PLL0_RESET_IN]

#SFP ports
set_property LOC R23  [get_ports {SFP_LOS_IN[0]}]
set_property LOC R18  [get_ports {SFP_TX_DISABLE_OUT[0]}]

#Test point TXUSRCLK on user_clk_p (J31)
set_property LOC J23 [get_ports gt0_txusrclk_o]
set_property IOSTANDARD LVCMOS25  [get_ports gt0_txusrclk_o]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
#Area group to help with timing if necessary
#create_pblock pblock_picxos
#resize_pblock pblock_picxos -add CLOCKREGION_X0Y0:CLOCKREGION_X0Y0

















