################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 3.0
##  \   \         Application : XAPP589, All digital VCXO.
##  /   /         Filename : VC709_picxo_example.xdc
## /___/   /\     Target board : VC709
## \   \  /  \    Timestamp : v25_0 @ Fri Apr  8 11:26:58 +0100 2016 Rev: 815:817
##  \___\/\___\
##
##
## USER CONSTRAINTS FILE FOR MGT WRAPPER EXAMPLE DESIGN
## Generated by Xilinx 7 Series FPGAs Transceivers Wizard
##
## Device:  xc7vx690t
## Package: ffg1761
##
## (c) Copyright 2010-2011 Xilinx, Inc. All rights reserved.
##
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
##
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
## 
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES. 
############################################################

##### test points##########
#J32
set_property LOC AK32 [get_ports gt0_rxoutclk_i_o]
#J31
set_property LOC AJ32 [get_ports gt0_txoutclk_i_o]
#LED0
set_property LOC AM39 [get_ports drpclk_in_i_o]

set_property IOSTANDARD LVCMOS18 [get_ports {gt0_rxoutclk_i_o gt0_txoutclk_i_o drpclk_in_i_o}]

#GT connections to HTG-FMC-SMA_LVDS Rev 1.0
#set_property LOC  GTHE2_CHANNEL_X1Y32 [get_cells gtwizard_v2_4_init_i/gtwizard_v2_4_i/gt0_gtwizard_v2_4_i/gthe2_i]
#set_property LOC G9 [get_ports Q0_CLK1_GTREFCLK_PAD_N_IN]
#set_property LOC G10 [get_ports Q0_CLK1_GTREFCLK_PAD_P_IN]

#set_property LOC  GTHE2_CHANNEL_X1Y33 [get_cells gtwizard_v2_4_init_i/gtwizard_v2_4_i/gt1_gtwizard_v2_4_i/gthe2_i]
#set_property LOC  GTHE2_CHANNEL_X1Y34 [get_cells gtwizard_v2_4_init_i/gtwizard_v2_4_i/gt2_gtwizard_v2_4_i/gthe2_i]
#set_property LOC  GTHE2_CHANNEL_X1Y35 [get_cells gtwizard_v2_4_init_i/gtwizard_v2_4_i/gt3_gtwizard_v2_4_i/gthe2_i]

#GT connections to SFP
set_property LOC  GTHE2_CHANNEL_X1Y12 [get_cells gtwizard_v2_4_init_i/gtwizard_v2_4_i/gt0_gtwizard_v2_4_i/gthe2_i]
set_property LOC  GTHE2_CHANNEL_X1Y13 [get_cells gtwizard_v2_4_init_i/gtwizard_v2_4_i/gt1_gtwizard_v2_4_i/gthe2_i]
set_property LOC  GTHE2_CHANNEL_X1Y14 [get_cells gtwizard_v2_4_init_i/gtwizard_v2_4_i/gt2_gtwizard_v2_4_i/gthe2_i]
set_property LOC  GTHE2_CHANNEL_X1Y15 [get_cells gtwizard_v2_4_init_i/gtwizard_v2_4_i/gt3_gtwizard_v2_4_i/gthe2_i]

##SMA clock
#set_property LOC AK7 [get_ports Q0_CLK1_GTREFCLK_PAD_N_IN]
#set_property LOC AK8 [get_ports Q0_CLK1_GTREFCLK_PAD_P_IN]
#SI5324 clock
set_property LOC AH7 [get_ports Q0_CLK1_GTREFCLK_PAD_N_IN]
set_property LOC AH8 [get_ports Q0_CLK1_GTREFCLK_PAD_P_IN]

#Area group to help with timing if necessary
create_pblock pblock_picxos
resize_pblock pblock_picxos -add CLOCKREGION_X1Y3:CLOCKREGION_X1Y3
#add_cells_to_pblock  pblock_picxos [get_cells {picxo_0 picxo_1 picxo_2 picxo_3}] 

#IOSTANDARDS
set_property IOSTANDARD LVCMOS18 [get_ports {QPLL_RESET_IN SYS_RESET_IN CPU_RST I2C_DATA I2C_CLK I2C_MUX_RESET_B\
                                  SI5324_RST_N SI5324_LOL\
                                  UART_TX UART_RX\
                                  SFP_TX_FAULT_IN SFP_TX_DISABLE_OUT SFP_MOD_DETECT_IN SFP_RS0_OUT SFP_RS1_OUT SFP_LOS_IN\
                                  }]; 
set_property IOSTANDARD LVDS [get_ports {SYS_CLK_P SYS_CLK_N}];

#SYS_CLK at 200MHz
set_property LOC H19 [get_ports SYS_CLK_P]
set_property LOC G18 [get_ports SYS_CLK_N]

#Resets, unused
set_property LOC AR40 [get_ports SYS_RESET_IN]
set_property LOC AP40 [get_ports QPLL_RESET_IN]
set_property LOC AV40 [get_ports CPU_RST]

#I2C control of SI5324
set_property LOC AT35 [get_ports I2C_CLK]
set_property LOC AU32 [get_ports I2C_DATA]
set_property LOC AY42 [get_ports I2C_MUX_RESET_B]
set_property LOC AT36 [get_ports SI5324_RST_N]
set_property LOC AU34 [get_ports SI5324_LOL]

#UART
set_property PACKAGE_PIN AU33 [get_ports UART_RX]
set_property PACKAGE_PIN AU36 [get_ports UART_TX]

#SFP ports
set_property LOC Y38 [get_ports {SFP_TX_FAULT_IN[0]}]
set_property LOC AB41 [get_ports {SFP_TX_DISABLE_OUT[0]}]
set_property LOC AB42 [get_ports {SFP_MOD_DETECT_IN[0]}]
set_property LOC W40 [get_ports {SFP_RS0_OUT[0]}]
set_property LOC Y40 [get_ports {SFP_RS1_OUT[0]}]
set_property LOC Y39 [get_ports {SFP_LOS_IN[0]}]

set_property LOC AA39 [get_ports {SFP_TX_FAULT_IN[1]}]
set_property LOC Y42 [get_ports {SFP_TX_DISABLE_OUT[1]}]
set_property LOC AA42 [get_ports {SFP_MOD_DETECT_IN[1]}]
set_property LOC AB38 [get_ports {SFP_RS0_OUT[1]}]
set_property LOC AB39 [get_ports {SFP_RS1_OUT[1]}]
set_property LOC AA40 [get_ports {SFP_LOS_IN[1]}]


set_property LOC AA41  [get_ports {SFP_TX_FAULT_IN[2]}]
set_property LOC AC38 [get_ports {SFP_TX_DISABLE_OUT[2]}]
set_property LOC AC39 [get_ports {SFP_MOD_DETECT_IN[2]}]
set_property LOC AD42  [get_ports {SFP_RS0_OUT[2]}]
set_property LOC AE42  [get_ports {SFP_RS1_OUT[2]}]
set_property LOC AD38  [get_ports {SFP_LOS_IN[2]}]

set_property LOC AE38 [get_ports {SFP_TX_FAULT_IN[3]}]
set_property LOC AC40 [get_ports {SFP_TX_DISABLE_OUT[3]}]
set_property LOC AC41 [get_ports {SFP_MOD_DETECT_IN[3]}]
set_property LOC AE39 [get_ports {SFP_RS0_OUT[3]}]
set_property LOC AE40 [get_ports {SFP_RS1_OUT[3]}]
set_property LOC AD40 [get_ports {SFP_LOS_IN[3]}]

set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CFGBVS GND [current_design]














