################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 3.0
##  \   \         Application : XAPP589, All digital VCXO.
##  /   /         Filename : ZC706_picxo_example.xdc
## /___/   /\     Target board : ZC706
## \   \  /  \    Timestamp : v25_0 @ Fri Apr  8 11:26:58 +0100 2016 Rev: 815:817
##  \___\/\___\
##
##
## USER CONSTRAINTS FILE FOR MGT WRAPPER EXAMPLE DESIGN
## Generated by Xilinx 7 Series FPGAs Transceivers Wizard
##
## Device:  xc7z045ffg900-2
## Package: ffg900
##
## (c) Copyright 2010-2011 Xilinx, Inc. All rights reserved.
##
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
##
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
## 
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES. 

############################################################

##SFP+
set_property LOC GTXE2_CHANNEL_X0Y10 [get_cells gtwizard_v2_4_i/gt0_gtwizard_v2_4_i/gtxe2_i]

set_property IOSTANDARD LVCMOS25 [get_ports CPLL_LOCK]
set_property IOSTANDARD LVCMOS15 [get_ports PRBS_ERR]
set_property IOSTANDARD LVCMOS15 [get_ports SYS_RST]
set_property IOSTANDARD LVCMOS18 [get_ports GTX0_RXUSERCLK_OUT]
set_property IOSTANDARD LVCMOS18 [get_ports GTX0_TXUSERCLK_OUT]
set_property IOSTANDARD LVDS [get_ports SYS_CLK_P]
set_property IOSTANDARD LVDS [get_ports SYS_CLK_N]

# LED 0
set_property LOC Y21 [get_ports CPLL_LOCK] 
# LED 1
set_property LOC G2 [get_ports PRBS_ERR]
# PL_CPU_RESET
set_property LOC A8 [get_ports SYS_RST] 
# 200MHz clock
set_property LOC H9 [get_ports SYS_CLK_P]
set_property LOC G9 [get_ports SYS_CLK_N]
# USER SMA REFCLK
set_property LOC W7 [get_ports Q2_CLK1_GTREFCLK_PAD_N_IN] 
set_property LOC W8 [get_ports Q2_CLK1_GTREFCLK_PAD_P_IN]
# USER_SMA_CLK_P
set_property LOC AD18 [get_ports GTX0_RXUSERCLK_OUT] 
# USER_SMA_CLK_N
set_property LOC AD19 [get_ports GTX0_TXUSERCLK_OUT] 
















